# Generated by Django 5.2.7 on 2025-10-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellido_materno',
            field=models.CharField(default='sin Nombre', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellido_paterno',
            field=models.CharField(default='sin apellido', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='sin nobmre', max_length=255),
            preserve_default=False,
        ),
    ]
