# Generated by Django 5.2.7 on 2025-10-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usuario_apellido_materno_usuario_apellido_paterno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
