# Generated by Django 5.2.7 on 2025-10-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_promocion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='estado_pago',
            field=models.BooleanField(default=False),
        ),
    ]
