# Generated by Django 5.2.7 on 2025-10-21 01:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_suscripcion_estado_pago'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-fecha_pago'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.RenameField(
            model_name='pago',
            old_name='monto_total',
            new_name='monto',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='promocion',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='suscripcion',
        ),
        migrations.AddField(
            model_name='pago',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AddField(
            model_name='pago',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 21, 1, 51, 42, 686227, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='referencia',
            field=models.CharField(blank=True, help_text='N° de transacción, comprobante, etc.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='tipo_pago',
            field=models.CharField(choices=[('suscripcion', 'Suscripción'), ('promocion', 'Promoción')], default='suscripcion', max_length=20),
        ),
        migrations.AddField(
            model_name='pago',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó el pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta de crédito/débito'), ('transferencia', 'Transferencia bancaria'), ('efectivo', 'Efectivo'), ('qr', 'Pago QR')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Comprobante',
        ),
    ]
