# Generated by Django 5.2.7 on 2025-10-21 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_pago_options_rename_monto_total_pago_monto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscripcion',
            name='estado_pago',
        ),
        migrations.CreateModel(
            name='SuscripcionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_pago', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='app.cliente')),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.suscripcion')),
            ],
            options={
                'verbose_name': 'Suscripción Cliente',
                'verbose_name_plural': 'Suscripciones Clientes',
                'unique_together': {('cliente', 'suscripcion')},
            },
        ),
    ]
